name: Build r619ac firmware

on:
  release:
    types: published
  push:
    branches:
      - master
  # schedule:
  #   - cron: 0 8 * * 5
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
        - uses: actions/checkout@v1
        
        - run: mkdir -p path/to/artifact
        
        - run: echo hello > path/to/artifact/world.txt

        - uses: actions/upload-artifact@v1
            with:
                name: my-artifact
                path: path/to/artifact
            with:
                name: test
                path: ./path